/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as PurchasesRouteRouteImport } from './routes/purchases/route'
import { Route as ProjectionsRouteRouteImport } from './routes/projections/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ListRouteRouteImport } from './routes/list/route'
import { Route as InvestmentsRouteRouteImport } from './routes/investments/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as GoalsRouteRouteImport } from './routes/goals/route'
import { Route as ForgotPasswordRouteRouteImport } from './routes/forgot-password/route'
import { Route as FamilyRouteRouteImport } from './routes/family/route'
import { Route as EducationRouteRouteImport } from './routes/education/route'
import { Route as CreditCardsRouteRouteImport } from './routes/credit-cards/route'
import { Route as BudgetsRouteRouteImport } from './routes/budgets/route'
import { Route as BankRouteRouteImport } from './routes/bank/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AchievementsRouteRouteImport } from './routes/achievements/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteRouteImport } from './routes/admin/users/route'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminSecurityRouteRouteImport } from './routes/admin/security/route'
import { Route as AdminReportsRouteRouteImport } from './routes/admin/reports/route'
import { Route as AdminNotificationsRouteRouteImport } from './routes/admin/notifications/route'
import { Route as AdminMarketInsightsRouteRouteImport } from './routes/admin/market-insights/route'
import { Route as AdminLogsRouteRouteImport } from './routes/admin/logs/route'
import { Route as AdminAuditRouteRouteImport } from './routes/admin/audit/route'

const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRouteRoute = PurchasesRouteRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionsRouteRoute = ProjectionsRouteRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRouteRoute = ListRouteRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRouteRoute = InvestmentsRouteRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRouteRoute = GoalsRouteRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRouteRoute = FamilyRouteRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRouteRoute = EducationRouteRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditCardsRouteRoute = CreditCardsRouteRouteImport.update({
  id: '/credit-cards',
  path: '/credit-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRouteRoute = BudgetsRouteRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRouteRoute = BankRouteRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRouteRoute = AchievementsRouteRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRouteRoute = AdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityRouteRoute = AdminSecurityRouteRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRouteRoute = AdminReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRouteRoute = AdminNotificationsRouteRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketInsightsRouteRoute =
  AdminMarketInsightsRouteRouteImport.update({
    id: '/market-insights',
    path: '/market-insights',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminLogsRouteRoute = AdminLogsRouteRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRouteRoute = AdminAuditRouteRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bank': typeof BankRouteRoute
  '/budgets': typeof BudgetsRouteRoute
  '/credit-cards': typeof CreditCardsRouteRoute
  '/education': typeof EducationRouteRoute
  '/family': typeof FamilyRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/goals': typeof GoalsRouteRoute
  '/home': typeof HomeRouteRoute
  '/investments': typeof InvestmentsRouteRoute
  '/list': typeof ListRouteRoute
  '/login': typeof LoginRouteRoute
  '/projections': typeof ProjectionsRouteRoute
  '/purchases': typeof PurchasesRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/signup': typeof SignupRouteRoute
  '/admin/audit': typeof AdminAuditRouteRoute
  '/admin/logs': typeof AdminLogsRouteRoute
  '/admin/market-insights': typeof AdminMarketInsightsRouteRoute
  '/admin/notifications': typeof AdminNotificationsRouteRoute
  '/admin/reports': typeof AdminReportsRouteRoute
  '/admin/security': typeof AdminSecurityRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bank': typeof BankRouteRoute
  '/budgets': typeof BudgetsRouteRoute
  '/credit-cards': typeof CreditCardsRouteRoute
  '/education': typeof EducationRouteRoute
  '/family': typeof FamilyRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/goals': typeof GoalsRouteRoute
  '/home': typeof HomeRouteRoute
  '/investments': typeof InvestmentsRouteRoute
  '/list': typeof ListRouteRoute
  '/login': typeof LoginRouteRoute
  '/projections': typeof ProjectionsRouteRoute
  '/purchases': typeof PurchasesRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/signup': typeof SignupRouteRoute
  '/admin/audit': typeof AdminAuditRouteRoute
  '/admin/logs': typeof AdminLogsRouteRoute
  '/admin/market-insights': typeof AdminMarketInsightsRouteRoute
  '/admin/notifications': typeof AdminNotificationsRouteRoute
  '/admin/reports': typeof AdminReportsRouteRoute
  '/admin/security': typeof AdminSecurityRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRouteRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bank': typeof BankRouteRoute
  '/budgets': typeof BudgetsRouteRoute
  '/credit-cards': typeof CreditCardsRouteRoute
  '/education': typeof EducationRouteRoute
  '/family': typeof FamilyRouteRoute
  '/forgot-password': typeof ForgotPasswordRouteRoute
  '/goals': typeof GoalsRouteRoute
  '/home': typeof HomeRouteRoute
  '/investments': typeof InvestmentsRouteRoute
  '/list': typeof ListRouteRoute
  '/login': typeof LoginRouteRoute
  '/projections': typeof ProjectionsRouteRoute
  '/purchases': typeof PurchasesRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/signup': typeof SignupRouteRoute
  '/admin/audit': typeof AdminAuditRouteRoute
  '/admin/logs': typeof AdminLogsRouteRoute
  '/admin/market-insights': typeof AdminMarketInsightsRouteRoute
  '/admin/notifications': typeof AdminNotificationsRouteRoute
  '/admin/reports': typeof AdminReportsRouteRoute
  '/admin/security': typeof AdminSecurityRouteRoute
  '/admin/settings': typeof AdminSettingsRouteRoute
  '/admin/users': typeof AdminUsersRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/bank'
    | '/budgets'
    | '/credit-cards'
    | '/education'
    | '/family'
    | '/forgot-password'
    | '/goals'
    | '/home'
    | '/investments'
    | '/list'
    | '/login'
    | '/projections'
    | '/purchases'
    | '/settings'
    | '/signup'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/market-insights'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/bank'
    | '/budgets'
    | '/credit-cards'
    | '/education'
    | '/family'
    | '/forgot-password'
    | '/goals'
    | '/home'
    | '/investments'
    | '/list'
    | '/login'
    | '/projections'
    | '/purchases'
    | '/settings'
    | '/signup'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/market-insights'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/bank'
    | '/budgets'
    | '/credit-cards'
    | '/education'
    | '/family'
    | '/forgot-password'
    | '/goals'
    | '/home'
    | '/investments'
    | '/list'
    | '/login'
    | '/projections'
    | '/purchases'
    | '/settings'
    | '/signup'
    | '/admin/audit'
    | '/admin/logs'
    | '/admin/market-insights'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRouteRoute: typeof AchievementsRouteRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BankRouteRoute: typeof BankRouteRoute
  BudgetsRouteRoute: typeof BudgetsRouteRoute
  CreditCardsRouteRoute: typeof CreditCardsRouteRoute
  EducationRouteRoute: typeof EducationRouteRoute
  FamilyRouteRoute: typeof FamilyRouteRoute
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRoute
  GoalsRouteRoute: typeof GoalsRouteRoute
  HomeRouteRoute: typeof HomeRouteRoute
  InvestmentsRouteRoute: typeof InvestmentsRouteRoute
  ListRouteRoute: typeof ListRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  ProjectionsRouteRoute: typeof ProjectionsRouteRoute
  PurchasesRouteRoute: typeof PurchasesRouteRoute
  SettingsRouteRoute: typeof SettingsRouteRoute
  SignupRouteRoute: typeof SignupRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projections': {
      id: '/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof ProjectionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-cards': {
      id: '/credit-cards'
      path: '/credit-cards'
      fullPath: '/credit-cards'
      preLoaderRoute: typeof CreditCardsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/market-insights': {
      id: '/admin/market-insights'
      path: '/market-insights'
      fullPath: '/admin/market-insights'
      preLoaderRoute: typeof AdminMarketInsightsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRouteRoute: typeof AdminAuditRouteRoute
  AdminLogsRouteRoute: typeof AdminLogsRouteRoute
  AdminMarketInsightsRouteRoute: typeof AdminMarketInsightsRouteRoute
  AdminNotificationsRouteRoute: typeof AdminNotificationsRouteRoute
  AdminReportsRouteRoute: typeof AdminReportsRouteRoute
  AdminSecurityRouteRoute: typeof AdminSecurityRouteRoute
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRoute
  AdminUsersRouteRoute: typeof AdminUsersRouteRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRouteRoute: AdminAuditRouteRoute,
  AdminLogsRouteRoute: AdminLogsRouteRoute,
  AdminMarketInsightsRouteRoute: AdminMarketInsightsRouteRoute,
  AdminNotificationsRouteRoute: AdminNotificationsRouteRoute,
  AdminReportsRouteRoute: AdminReportsRouteRoute,
  AdminSecurityRouteRoute: AdminSecurityRouteRoute,
  AdminSettingsRouteRoute: AdminSettingsRouteRoute,
  AdminUsersRouteRoute: AdminUsersRouteRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRouteRoute: AchievementsRouteRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BankRouteRoute: BankRouteRoute,
  BudgetsRouteRoute: BudgetsRouteRoute,
  CreditCardsRouteRoute: CreditCardsRouteRoute,
  EducationRouteRoute: EducationRouteRoute,
  FamilyRouteRoute: FamilyRouteRoute,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRoute,
  GoalsRouteRoute: GoalsRouteRoute,
  HomeRouteRoute: HomeRouteRoute,
  InvestmentsRouteRoute: InvestmentsRouteRoute,
  ListRouteRoute: ListRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  ProjectionsRouteRoute: ProjectionsRouteRoute,
  PurchasesRouteRoute: PurchasesRouteRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  SignupRouteRoute: SignupRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
