name: CI

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]

jobs:
    quality-checks:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10.14.0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Ensure SECURITY.md files exist
              run: |
                  for f in ./SECURITY.md ../shop-wise-api/SECURITY.md ../shop-wise-app/SECURITY.md; do
                    if [ ! -f "$f" ]; then echo "Missing $f"; exit 1; fi
                  done

            - name: Run security audit
              run: pnpm audit --audit-level high
            - name: Check code formatting
              run: pnpm exec prettier --check .

            - name: Run TypeScript type checking
              run: pnpm run typecheck

            - name: Run tests
              run: pnpm test

            - name: Build project
              run: pnpm run build

    codeql-analysis:
        runs-on: ubuntu-latest
        needs: quality-checks
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v2
              with:
                  languages: javascript

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v2
